# travis
sudo: false
language: python
cache: pip

python:
  - 3.6

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=flake8
      after_success:
        - echo "done"

    - python: 3.6
      env: TOXENV=docs
      after_success:
        - echo "done"

    - python: 3.6
      env: TOXENV=docs-links
      after_success:
        - echo "done"

    - language: python
      sudo: required
      dist: xenial
      python: "3.7"
      env: linux-py37

    - language: generic
      python: 3.6
      env: osx-py36
      os: osx
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda update conda -y
        - conda create -n py36 python=3.6 -y
      install:
        - source activate py36
        - conda config --add channels conda-forge
        - conda install -y --name py36 tox coveralls
        - pip freeze
      script: tox -e py36

    - language: generic
      python: 3.7
      env: osx-py37
      os: osx
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda update conda -y
        - conda create -n py37 python=3.7 -y
      install:
        - source activate py37
        - conda config --add channels conda-forge
        - conda install -y --name py37 tox coveralls
        - pip freeze
      script: tox -e py37

  allow_failures:
    #      this tests are allowed to fail since they rely external resources
    - env: TOXENV=docs-links

install:
  - python -m pip install -U pip>=8.1.2
  - pip install tox-travis coveralls

script: tox

after_success:
  - coveralls
  - coverage erase

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: s-weigand
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: s-weigand/flake8_nb
    python: 3.7
