channels:
  - conda-forge
dependencies:
  # Jupyter
  - jupyterlab=2
  - nodejs=12
  - widgetsnbextension=3.5
  # Python Kernel
  - python=3.7
  - pip
  - pip:
      - git+https://github.com/s-weigand/flake8-nb.git
