name: "Scheduled Tests"
on:
  schedule:
    - cron: "0 7 * * 1" # At 07:00 on each Monday.

jobs:
  flake8-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U -c constraints.txt -r requirements_dev.txt
          python -m pip install -U -q git+https://gitlab.com/pycqa/flake8.git
      - name: Run tests
        env:
          TOX_ENV_NAME: flake8-nightly
        run: |
          py.test -vv --cov=./ --cov-report term --cov-report xml --cov-config .coveragerc tests
